# EU AI Act - Article 50 Transparency Obligations for Deployers
# Version: 2026.0
# Effective: 2026-08-02 (Article 50 transparency obligations apply from this date)
# Source: https://eur-lex.europa.eu/eli/reg/2024/1689/oj (Article 50)
#
# Deployers of AI systems that generate synthetic content (text, image, audio, video)
# must ensure outputs are marked as artificially generated or manipulated in a
# machine-readable format and clearly disclosed to recipients.

package m3m3tic.policy.eu.ai_act_article50

import data.m3m3tic.policy.interface as iface

eu_geos := [
	"AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR",
	"DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL",
	"PL", "PT", "RO", "SK", "SI", "ES", "SE",
]

# Self-selection: applies when any EU geo is targeted
applicable {
	iface.any_geo_applicable(input.content.audience.geos, eu_geos)
}

# Deny: AI-generated content without AI disclosure label
deny[result] {
	applicable
	iface.content_is_ai_generated(input)
	not has_ai_disclosure
	result := iface.make_result(
		"ai-act-art50-gen-label-001",
		"block",
		"AI Act Article 50(2): Content generated by AI systems must be labelled as artificially generated in a machine-readable way and clearly disclosed.",
		"EU",
		"Add AI-generated content disclosure. Include machine-readable metadata (C2PA/IPTC) marking content as AI-generated AND visible text label for recipients.",
	)
}

# Deny: AI-generated content without machine-readable provenance
deny[result] {
	applicable
	iface.content_is_ai_generated(input)
	not has_machine_readable_provenance
	result := iface.make_result(
		"ai-act-art50-machine-readable-002",
		"block",
		"AI Act Article 50(2): AI-generated content must be marked in a machine-readable format to enable detection.",
		"EU",
		"Embed C2PA manifest, IPTC AI metadata, or equivalent machine-readable provenance signal indicating AI generation.",
	)
}

# Warn: AI-assisted content should also carry disclosure
deny[result] {
	applicable
	iface.content_is_ai_assisted(input)
	not iface.content_is_ai_generated(input)
	not has_ai_disclosure
	result := iface.make_result(
		"ai-act-art50-assisted-003",
		"warn",
		"AI Act Article 50: AI-assisted content (materially modified by AI) should be disclosed. Obligation scope includes manipulated content.",
		"EU",
		"Consider adding an AI-assisted disclosure if the AI contribution is material to the final creative output.",
	)
}

# Deny: deep fake / synthetic media without explicit labeling
deny[result] {
	applicable
	iface.content_is_ai_generated(input)
	is_synthetic_media
	not has_synthetic_media_label
	result := iface.make_result(
		"ai-act-art50-deepfake-004",
		"block",
		"AI Act Article 50(4): Deep fakes must be disclosed with a label stating content has been artificially generated or manipulated.",
		"EU",
		"Add prominent 'This content is AI-generated' label. For video/audio, the disclosure must appear at the start and in the description.",
	)
}

has_ai_disclosure {
	disc := input.content.disclosures_attached[_]
	disc.type == "ai_generated"
}

has_ai_disclosure {
	disc := input.content.disclosures_attached[_]
	disc.type == "ai_assisted"
}

has_machine_readable_provenance {
	disc := input.content.disclosures_attached[_]
	disc.type == "ai_generated"
	disc.method == "c2pa"
}

has_machine_readable_provenance {
	disc := input.content.disclosures_attached[_]
	disc.type == "ai_generated"
	disc.method == "iptc"
}

has_machine_readable_provenance {
	disc := input.content.disclosures_attached[_]
	disc.type == "ai_generated"
	disc.method == "machine_readable"
}

is_synthetic_media {
	input.content.medium.placement == "video"
}

is_synthetic_media {
	input.content.medium.placement == "reels"
}

is_synthetic_media {
	input.content.medium.placement == "stories"
}

is_synthetic_media {
	contains(input.content.medium.placement, "video")
}

has_synthetic_media_label {
	disc := input.content.disclosures_attached[_]
	disc.type == "ai_generated"
	disc.method == "superimposed"
}

has_synthetic_media_label {
	disc := input.content.disclosures_attached[_]
	disc.type == "ai_generated"
	disc.method == "platform_native"
}
